### ISSUE TITLE
API not setting stopLoss and takeProfit

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [phemex/phemex-python-api#1]
I'm trying to set an order with stop loss and take profit like this
`client.place_order({"symbol":"DOGEUSD","clOrdID":"cryptomarauder1","side":Client.SIDE_BUY,"orderQty":1000,"ordType":Client.ORDER_TYPE_MARKET,"priceEp":0.2250,"takeProfitEp":0.25,"stopLossEp":0.20})`
The problem is, the api is ignoring takeProfitEp and stopLossEp. An order is created, but the SL and TP isn't set.

**Comment by Saschax99** [comment]
Hey I had the same Issue. Don't ask me why, but you need to **multiply** takeProfit and stopLoss by **10000**. My function works fine and correct with this fix. It's going to look like this:

`params = {'takeProfitEp': (3450*10000), 'stopLossEp': (3370*10000)}`
`exchange.create_order("ETH/USD:USD", "market" , "buy", 1, params=params)`

Have a nice day

**Comment by Karlheinzniebuhr** [comment]
Thanks for pointing out, turns out you need to set the scaled price multiplying by 10000, [here ](takeProfitEp)is some documentation on that

**Comment by zonian1** [comment]
Thanks Saschax99. My mind is blown. How did you find out about this ? (I have tried it just now, it is working for a fact)

` symbol = 'BTC/USD:USD'
type = 'Limit'
side = 'buy'
amount = 1
price = 35000

params = {
    'stopLossEp': 333700000 ,
    'takeProfitEp': 400500000,
    'timeInForce': 'PostOnly',
    'reduceOnly': False
}

stop_limit = exchange.create_order(symbol, type, side, amount, price, params)
print(stop_limit) `

The link is not working Karlheinzniebuhr. :)

**Comment by Saschax99** [comment]
Hey zonian1, 
i don't know exactly, i noticed it while debugging.
I think its because the values you enter are given in micro parameters (10^-6). So you need to multiply it by 10000 to reach standard parameters (10^0)

**Comment by Giits254** [comment]
am trying to use this in USDT -M but its ignoring the tp and sl orders.. how do I go about it       
           
params = {'posSide': 'Long','takeProfitEp': (400500000), 'stopLossEp': (397000000),}

order = exchange.create_order(
    symbol="BTC/USDT:USDT",
    side="buy",
    type="limit",
    price="39915",  # This will be ignored because we have specified type as "market
    amount=0.01,
    params=params,
)
