### ISSUE TITLE
Phemex Leverage Trading with API

### ISSUE THREAD

**Issue by dani-s-92** [phemex/phemex-python-api#4]
Hello,

can someone tell how to set a a leverage order with the api. For example with leverage 5 for a long trade for market conditions. In the ideal case a stop loss mark and a take profit mark is included.

Thank you!

Best regards
Daniel

**Comment by Karlheinzniebuhr** [comment]
You can set leverage like this (taken from the [example code](https://github.com/phemex/phemex-python-api/blob/ebc03234a5cff7940adecd7a87df6abd3c0516cc/examples/rest.py)):
```
# Set leverage
try:
    # Set 0 to change back to cross margin
    # Set to 10x 
    r = client.change_leverage(Client.SYMBOL_BTCUSD, 10)
    print("response:" + str(r))
except PhemexAPIException as e:
    print(e)
```

**Comment by dani-s-92** [comment]
Thank you for your answer and sorry for asking again. 
This code snippet shows how to change leverage. But now I have to place an order with this leverage. How can I do that?

**Comment by dani-s-92** [comment]
Solved
